version: "3.2"

services:
  app:
    image: linuxserver/sonarr
    volumes:
      - config:/config
      - /mnt/Media:/media
      - /home/transmission/misc/downloads:/downloads
      - /mnt:/input
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8989:8989
    environment:
      - 'TZ=Europe/London'
      - 'PUID=1000'
      - 'PGID=1000'
volumes:
  config:
  media:
  downloads:
  input:

