version: "3.2"

services:
  app:
    image: linuxserver/sonarr
    volumes:
      - config:/config
      - tv:/tv
      - downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8989:8989
    environment:
      - 'TZ=Europe/London'
volumes:
  config:
  tv:
  downloads:

