#!/bin/bash

# Checking it's running as sudo

if [ "$EUID" -ne 0 ]
  then echo "Please, run the installation as root or with sudo"
  exit
fi

#apt-get update
apt-get install -y git 

git config --global credential.helper "cache --timeout=36000000"

git clone https://github.com/gncabrera/kirios-tools.git /opt/kirios

ln -s /opt/kirios/kirios.py /usr/bin/kirios
chmod 755 /usr/bin/kirios
chown root:root /usr/bin/kirios


kirios --version
kirios update