version: "3.2"

services:
  app:
    image: linuxserver/hydra
    volumes:
      - /home/hydra/config:/config
      - /home/hydra/downloads:/downloads
    ports:
      - 5075:5075
    environment:
      - 'TZ=Europe/London'
      - 'PUID=1000'
      - 'PGID=1000'
volumes:
  config:
  downloads:
