version: '3.3'

services:
   db:
     image: mysql:5.5
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_DATABASE: nextcloud
       MYSQL_ROOT_PASSWORD: somenextcloud
       MYSQL_DATABASE: nextcloud
       MYSQL_USER: nextcloud
       MYSQL_PASSWORD: nextcloud

   nextcloud:
     depends_on:
       - db
     image: nextcloud:13.0.5
     ports:
       - "8070:80"
     restart: always
     volumes:
       - nextcloud:/var/www/html
     environment:
       MYSQL_DATABASE: nextcloud
       MYSQL_USER: nextcloud
       MYSQL_PASSWORD: nextcloud
       MYSQL_HOST: db
volumes:
    db_data:
    nextcloud: