version: "3.2"

services:
  headphones:
    image: ghcr.io/linuxserver/headphones
    volumes:
      - /home/music-server/headphones/config:/config
      - /mnt/media:/mnt/media
    ports:
      - 8181:8181
    environment:
      - 'TZ=Europe/London'
      - 'PUID=1000'
      - 'PGID=1000'
