version: "3.2"

services:
  headphones:
    image: ghcr.io/linuxserver/headphones
    volumes:
      - /home/music-server/headphones/config:/config
      - /mnt/media:/mnt/media
    ports:
      - 8181:8181
    environment:
      - 'TZ=Europe/London'
      - 'PUID=1000'
      - 'PGID=1000'
  musicbrainz:
    image: linuxserver/musicbrainz:v-2019-08-08-ls6
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - BRAINZCODE=ceZHDYzZ57zeWwyemKhhOhw3VA9rxgeWZcjVYS2o 
      - WEBADDRESS=192.168.0.22
    volumes:
      - /home/music-server/musicbrainz/config:/config
      - /home/music-server/musicbrainz/data:/data
    ports:
      - 5005:5000
  airsonic:
    image: ghcr.io/linuxserver/airsonic
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/music-server/airsonic/config:/config
      - /mnt/media/Music:/music
      - /home/music-server/airsonic/playlists:/playlists
    ports:
      - 4040:4040
