version: "3.2"

services:
  app:
    image: linuxserver/sabnzbd
    volumes:
      - /home/sabnzbd/config:/config
      - /home/sabnzbd/downloads:/downloads
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      - 'TZ=Europe/London'
      - 'PUID=1000'
      - 'PGID=1000'
volumes:
  config:
  downloads:
