version: "3.2"

services:
  sonarr:
    image: linuxserver/sonarr
    volumes:
      - /mnt/Media:/mnt/Media
      - /home/server/sonarr/config:/config
      - /home/server/downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8989:8989
    environment:
      - 'TZ=Europe/London'
      - 'PUID=1000'
      - 'PGID=1000'
  radarr:
    image: linuxserver/radarr
    volumes:
      - /mnt/Media:/mnt/Media
      - /home/server/radarr/config:/config
      - /home/server/downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 7878:7878
    environment:
      - 'TZ=Europe/London'
      - 'PUID=1000'
      - 'PGID=1000'
  headphones:
    image: linuxserver/headphones
    volumes:
      - /mnt/Media:/mnt/Media
      - /home/server/headphones/config:/config
      - /home/server/downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8181:8181
    environment:
      - 'TZ=Europe/London'
      - 'PUID=1000'
      - 'PGID=1000'
  hydra:
    image: linuxserver/hydra
    volumes:
      - /home/server/hydra/config:/config
    ports:
      - 5075:5075
    environment:
      - 'TZ=Europe/London'
      - 'PUID=1000'
      - 'PGID=1000'
  cloudcmd:
    image: coderaiser/cloudcmd
    volumes:
      - /:/mnt/fs
    ports:
      - 7890:8000
  sabnzb:
    image: linuxserver/sabnzbd
    volumes:
      - /home/server/sabnzbd/config:/config
      - /home/server/downloads:/downloads
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      - 'TZ=Europe/London'
      - 'PUID=1000'
      - 'PGID=1000'
  syncthing:
    image: linuxserver/syncthing
    volumes:
      - /home/server/syncthing/config:/config
      - /home/server/downloads/syncthing_data1:/data1
      - /home/server/downloads/syncthing_data2:/data2
      - /home/server/downloads/syncthing_data3:/data3
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=<022>
  transmission_misc:
    image: linuxserver/transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/server/transmission_misc/config:/config
      - /home/server/transmission_misc/watch:/watch
      - /home/server/downloads:/downloads
    ports:
      - 9083:9091
      - 51483:51483
      - 51483:51483/udp
  deluge:
    image: linuxserver/deluge
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/server/deluge/config:/config
      - /mnt/Media/TorrentData/deluge:/downloads
  muximux:
    image: linuxserver/muximux
    container_name: muximux
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/server/muximux/config
    ports:
      - 8090:80
  glances:
    image: nicolargo/glances
    network_mode: host
    pid: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - GLANCES_OPT=-w
    volumes:
      - /home/server/glances/conf:/glances/conf
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 61208-61209:61208-61209
    


