version: "3.2"

services:
  sonarr:
    image: linuxserver/sonarr
    volumes:
      - /mnt/Media:/media
      - /mnt/Media/server/sonarr/config:/config
      - /mnt/Media/server/downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8989:8989
    environment:
      - 'TZ=Europe/London'
      - 'PUID=1000'
      - 'PGID=1000'
  radarr:
    image: linuxserver/radarr
    volumes:
      - /mnt/Media:/media
      - /mnt/Media/server/radarr/config:/config
      - /mnt/Media/server/downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 7878:7878
    environment:
      - 'TZ=Europe/London'
      - 'PUID=1000'
      - 'PGID=1000'
  hydra:
    image: linuxserver/hydra
    volumes:
      - /mnt/Media/server/hydra/config:/config
    ports:
      - 5075:5075
    environment:
      - 'TZ=Europe/London'
      - 'PUID=1000'
      - 'PGID=1000'
  cloudcmd:
    image: coderaiser/cloudcmd
    volumes:
      - /:/mnt/fs
    ports:
      - 7890:8000
  sabnzb:
    image: linuxserver/sabnzbd
    volumes:
      - /home/sabnzbd/config:/config
      - /home/sabnzbd/downloads:/nzb_downloads
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      - 'TZ=Europe/London'
      - 'PUID=1000'
      - 'PGID=1000'
  syncthing:
    image: linuxserver/syncthing
    volumes:
      - /mnt/Media/server/syncthing/config:/config
      - /mnt/Media/server/downloads/syncthing_data1:/data1
      - /mnt/Media/server/downloads/syncthing_data2:/data2
      - /mnt/Media/server/downloads/syncthing_data3:/data3
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=<022>
    
    


