version: "3.2"

services:
  app:
    image: linuxserver/beets
    volumes:
      -v /home/beets/config:/config \
      -v /home/beets/music:/music \
      -v /home/beets/downloads:/downloads \
    ports:
      - 8337:8337
    environment:
      - 'TZ=Europe/London'
      - 'PUID=1000'
      - 'PGID=1000'
volumes:
  config:
  music:
  downloads:
