version: "3.2"

services:
  app:
    image: horjulf/rutorrent-autodl
    volumes:
      - /home/rutorrent/config:/config
      - /home/rutorrent/downloads:/downloads
      - /home/rutorrent/downloads:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8170:80
      - 5000:5000
      - 51413:51413
      - 51413:51413/udp
    environment:
      - 'TZ=Europe/London'
      - 'PGID=0'
      - 'PUID=0'
volumes:
  config:

