#!/bin/bash

# DESCRIPTION: Installs Nextloud
# DEPENDENCIES: docker, rclone

docker pull ghcr.io/linuxserver/mariadb
docker pull ghcr.io/linuxserver/bookstack
kirios install service "/opt/kirios/applications/bookstack/bookstack.service"


echo ""
echo ""
echo "URL: http://localhost:6875"
echo ""
echo "Username: admin@admin.com"
echo "Password: password"
echo "Docker GitHub source: https://hub.docker.com/r/linuxserver/bookstack"
