version: '3.3'

services:
   db:
     image: mysql:5.7.21
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: secret
       MYSQL_DATABASE: bookstack
       MYSQL_USER: bookstack
       MYSQL_PASSWORD: secret

   bookstack:
     depends_on:
       - db
     image: solidnerd/bookstack:0.22.0
     ports:
       - "8050:80"
     restart: always
     volumes:
       - bookstack_uploads:/var/www/bookstack/public/uploads
       - bookstack_storage:/var/www/bookstack/public/storage
     environment:
       DB_HOST: db:3306
       DB_DATABASE: bookstack
       DB_USERNAME: bookstack
       DB_PASSWORD: secret
       APP_URL: https://wiki.kirios.co
volumes:
    db_data:
    bookstack_uploads:
    bookstack_storage: