---
version: "2"
services:
  bookstack:
    image: ghcr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=https://kb.kirios.com.ar
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=123456
      - DB_DATABASE=bookstackapp
    volumes:
      - /home/server/bookstack/config:/config
    ports:
      - 6875:80
    depends_on:
      - bookstack_db
  bookstack_db:
    image: ghcr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Europe/London
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=123456
    volumes:
      - /home/server/bookstack/db:/config
