version: '2'

services:
  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: filerun
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: filerun
    volumes:
      - /home/server/filerun/db:/var/lib/mysql

  web:
    image: afian/filerun
    environment:
      FR_DB_HOST: db
      FR_DB_PORT: 3306
      FR_DB_NAME: filerun
      FR_DB_USER: filerun
      FR_DB_PASS: 123456
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
    depends_on:
      - db
    links:
      - db:db
    ports:
      - "8033:80"
    volumes:
      - /home/server/filerun/html:/var/www/html
      - /home/server/filerun/user-files:/user-files