version: '3.3'

services:
   jenkins:
     image: jenkins/jenkins:2.141
     volumes:
       - jenkins_home:/var/jenkins_home
     ports:
       - "8000:8080"
       - "50000:50000"
     restart: always
volumes:
    jenkins_home: