version: '3.3'

services:
   jenkins:
     image: registry.gitlab.com/gncabrera/jenkins:latest
     volumes:
       - jenkins_home:/var/jenkins_home
     ports:
       - "8000:8080"
       - "50000:50000"
     restart: always
volumes:
    jenkins_home: