version: '3.3'

services:
   jenkins:
     image: kirios/media-server:jenkins
     privileged: true
     container_name: jenkins
     volumes:
       - /var/jenkins_home:/var/jenkins_home
       - /var/run/docker.sock:/var/run/docker.sock
       - /usr/bin/docker:/usr/bin/docker
       - /mnt/storage:/mnt/storage
       - /etc/localtime:/etc/localtime:ro
     ports:
       - "8000:8080"
       - "50000:50000"
     restart: always
volumes:
    jenkins_home:
