#!/bin/bash

SERVICE_PATH=$1
SERVICE_FILE=$(basename "$SERVICE_PATH")
SERVICE_NAME="${SERVICE_FILE%.*}"


if [[ $# -eq 0 ]] ; then
    echo 'Must specify service file path [/path/to/my-service.service]'
    exit 1
fi

echo "Installing service $SERVICE_NAME"

kirios uninstall service $SERVICE_NAME
cp $SERVICE_PATH /etc/systemd/system/$SERVICE_NAME.service
systemctl enable $SERVICE_NAME.service
systemctl start $SERVICE_NAME.service