version: "3.2"

services:
  app:
    image: plusminus/jdownloader2-headless
    volumes:
      - /home/server/jdownloader/config:/opt/JDownloader/cfg
      - /mnt/downloads/jdownloads:/opt/JDownloader/Downloads
    environment:
      - 'PUID=1000'
      - 'PGID=1000'
volumes:
  config:
  jdownloads:

