version: "3.2"

services:
  app:
    image: jlesage/jdownloader-2
    volumes:
      - /home/server/jdownloader/config:/config
      - /mnt/data/downloads/jdownloads:/output
    ports:
      - 5800:5800
    environment:
      - 'PUID=1000'
      - 'PGID=1000'

