---
version: "3.2"
services:
  dockerhost:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
  sonarr:
    image: linuxserver/sonarr:preview
    volumes:
      - /mnt/media:/mnt/media
      - /home/server/sonarr/config:/config
      - /home/server/downloads:/downloads
      - /mnt/downloads/rutorrent:/rutorrent
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8989:8989
    environment:
      - 'TZ=America/Buenos_Aires'
      - 'PUID=1000'
      - 'PGID=1000'
    depends_on:
      - dockerhost
  sonarr_la:
    image: linuxserver/sonarr:preview
    volumes:
      - /mnt/media:/mnt/media
      - /home/server/sonarr_la/config:/config
      - /home/server/downloads:/downloads
      - /mnt/downloads/rutorrent:/rutorrent
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8988:8989
    environment:
      - 'TZ=America/Buenos_Aires'
      - 'PUID=1000'
      - 'PGID=1000'
    depends_on:
      - dockerhost
  sonarr_es:
    image: linuxserver/sonarr:preview
    volumes:
      - /mnt/media:/mnt/media
      - /home/server/sonarr_es/config:/config
      - /home/server/downloads:/downloads
      - /mnt/downloads/rutorrent:/rutorrent
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8987:8989
    environment:
      - 'TZ=America/Buenos_Aires'
      - 'PUID=1000'
      - 'PGID=1000'
    depends_on:
      - dockerhost
  radarr:
    image: linuxserver/radarr:preview
    volumes:
      - /mnt/media:/mnt/media
      - /home/server/radarr/config:/config
      - /home/server/downloads:/downloads
      - /mnt/downloads/rutorrent:/rutorrent
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 7878:7878
    environment:
      - 'TZ=America/Buenos_Aires'
      - 'PUID=1000'
      - 'PGID=1000'
    depends_on:
      - dockerhost
  radarr_es:
    image: linuxserver/radarr:preview
    volumes:
      - /mnt/media:/mnt/media
      - /home/server/radarr_es/config:/config
      - /home/server/downloads:/downloads
      - /mnt/downloads/rutorrent:/rutorrent
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 7877:7878
    environment:
      - 'TZ=America/Buenos_Aires'
      - 'PUID=1000'
      - 'PGID=1000'
    depends_on:
      - dockerhost
  transmission_misc:
    image: linuxserver/transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Buenos_Aires
    volumes:
      - /home/server/transmission_misc/config:/config
      - /home/server/transmission_misc/watch:/watch
      - /home/server/downloads:/downloads
    ports:
      - 9083:9091
      - 51483:51483
      - 51483:51483/udp
  sabnzb:
    image: linuxserver/sabnzbd
    volumes:
      - /home/server/sabnzbd/config:/config
      - /home/server/downloads:/downloads
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      - 'TZ=America/Buenos_Aires'
      - 'PUID=1000'
      - 'PGID=1000'
  organizr:
    image: organizrtools/organizr-v2
    volumes:
      - /home/server/organizr/config:/config
    ports:
      - 80:80
    environment:
      - 'TZ=Europe/London'
    depends_on:
      - dockerhost  
  flexget:
    image: wiserain/flexget
    volumes:
      - /home/server/flexget/data:/data
      - /home/server/flexget/config:/config
    ports:
      - 5050:5050
    environment:
      - 'TZ=America/Buenos_Aires'
      - 'FG_LOG_LEVEL=info'
      - 'PUID=1000'
      - 'PGID=1000'
    depends_on:
      - dockerhost  
  
