---
version: "3.2"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /home/server/plex/config:/config
      - /mnt/media:/media
  sonarr:
    image: linuxserver/sonarr
    volumes:
      - /mnt/media:/mnt/media
      - /home/server/sonarr/config:/config
      - /home/server/downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8989:8989
    environment:
      - 'TZ=Europe/London'
      - 'PUID=1000'
      - 'PGID=1000'
  transmission_misc:
    image: linuxserver/transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/server/transmission_misc/config:/config
      - /home/server/transmission_misc/watch:/watch
      - /home/server/downloads:/downloads
    ports:
      - 9083:9091
      - 51483:51483
      - 51483:51483/udp
  
